name: ${plugin}
version: ${project.version}
main: ${package}
author: "CodeItAll"
website: https://codeitall.com/
description: "The ultimate way to make your server stand out from the rest."
softdepend: ["PlaceholderAPI", "WorldGuard"]

commands:
  levellingtools:
    description: ${plugin} commands
    usage: ""
    aliases: ["ltools", "tools", "tool", "lt", "leveltools"]

permissions:
  ltools.give:
    description: Give yourself or a player a levelling tool
  ltools.reload:
    description: Reload the configuration file into memory
  ltools.help:
    description: View commands you have access to within the plugin
  ltools.info:
    description: View information about the plugin
    default: true
  ltools.xp:
    description: View yourself or another players xp amount
    default: true